title_en: "Swapna Dutta"
title_bn: "স্বপ্না দত্ত"

description_en: "Na hanyate hanyamāne śarīre"
description_bn: "ন হন্যতে হন্যমানে শরীরে"

timezone: Asia/Kolkata

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - LICENSE
