title: "Swapna Dutta"
description: "Na hanyate hanyamāne śarīre"
timezone: Asia/Kolkata

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - LICENSE
