title: "Swapna Dutta"
description: "In loving memory"

timezone: Asia/Kolkata
lang: bn

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - LICENSE
